# Generated by Django 6.0.7 on 2026-09-02 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0004_adiciona_ano_letivo_e_historico'),
        ('livros', '0005_validar_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('DISPONIVEL', 'Disponível'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], db_index=True, default='AGUARDANDO', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('disponibilizada_em', models.DateTimeField(blank=True, null=True)),
                ('notificada_em', models.DateTimeField(blank=True, null=True)),
                ('disponivel_ate', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='alunos.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='livros.livro')),
            ],
            options={
                'ordering': ('criada_em', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('AGUARDANDO', 'DISPONIVEL'))), fields=('aluno', 'livro'), name='reserva_ativa_unica_aluno_livro')],
            },
        ),
    ]
