# Generated by Django 6.0.7 on 2026-09-01 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0004_adiciona_ano_letivo_e_historico'),
        ('emprestimos', '0003_fortalece_dominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATRASO', 'Empréstimo atrasado'), ('RESERVA', 'Reserva disponível'), ('PENDENCIA_ANUAL', 'Pendência anual')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('FALHA', 'Falha')], db_index=True, default='PENDENTE', max_length=10)),
                ('chave', models.CharField(max_length=160, unique=True)),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=160)),
                ('corpo', models.TextField()),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('ultima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='alunos.aluno')),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='emprestimos.emprestimo')),
            ],
            options={
                'ordering': ('criada_em',),
            },
        ),
    ]
