# Generated by Django 6.0.7 on 2026-09-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacoes', '0001_adiciona_caixa_saida'),
        ('reservas', '0001_cria_fila_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADA', 'Enviada'), ('FALHA', 'Falha')], db_index=True, default='PENDENTE', max_length=12),
        ),
    ]
