# Generated by Django 6.0.7 on 2026-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacoes', '0002_amplia_caixa_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('CADASTRO', 'Cadastro de aluno'), ('EMPRESTIMO', 'Empréstimo realizado'), ('PRAZO', 'Empréstimo perto do prazo'), ('ATRASO', 'Empréstimo atrasado'), ('RESERVA', 'Reserva disponível'), ('PENDENCIA_ANUAL', 'Pendência anual')], max_length=20),
        ),
    ]
