# Generated by Django 6.0.7 on 2026-08-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=10)),
                ('turma', models.CharField(max_length=10)),
                ('turno', models.CharField(choices=[('M', 'MATUTINO'), ('V', 'VESPERTINO')], max_length=1)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Aluno',
            },
        ),
    ]
