# Generated by Django 6.0.7 on 2026-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='turno',
            field=models.CharField(choices=[('M', 'MATUTINO'), ('V', 'VESPERTINO')], max_length=1),
        ),
    ]
