# Generated by Django 6.0.7 on 2026-08-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('emprestimos', '0002_renomeia_modelos_e_campos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
