# Generated by Django 6.0.7 on 2026-08-16 13:48

import alunos.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_renomeia_modelos_e_campos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('nome',), 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[alunos.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='matrícula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(max_length=20, verbose_name='série'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1),
        ),
    ]
