# Generated by Django 6.0.7 on 2026-08-31 23:57

import alunos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_fortalece_dominio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ano_letivo',
            field=models.PositiveSmallIntegerField(default=alunos.models.ano_letivo_atual),
        ),
        migrations.CreateModel(
            name='HistoricoProgressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_origem', models.PositiveSmallIntegerField()),
                ('ano_destino', models.PositiveSmallIntegerField()),
                ('serie_anterior', models.CharField(max_length=20)),
                ('serie_nova', models.CharField(blank=True, max_length=20)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressoes', to='alunos.aluno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
                'constraints': [models.UniqueConstraint(fields=('aluno', 'ano_destino'), name='historico_progressao_unica_por_ano')],
            },
        ),
    ]
