# Generated by Django 6.0.7 on 2026-08-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0003_fortalece_dominio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAZO', 'Prazo proximo'), ('ATRASO', 'Emprestimo atrasado')], max_length=10)),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.CharField(max_length=255)),
                ('lida', models.BooleanField(db_index=True, default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='emprestimos.emprestimo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criada_em',),
                'constraints': [models.UniqueConstraint(fields=('usuario', 'emprestimo', 'tipo'), name='notificacao_unica_usuario_emprestimo_tipo')],
            },
        ),
    ]
