# Generated by Django 6.0.7 on 2026-08-13 22:21


from django.contrib.auth.hashers import make_password
from django.db import migrations


def copiar_usuarios(apps, schema_editor):
    Usuariolegado = apps.get_model("usuarios", "Usuario")
    Perfil = apps.get_model("usuarios", "Perfil")
    User = apps.get_model("auth", "User")

    for legado in Usuariolegado.objects.all().iterator():
        prefixo = (legado.email.split("@")[0] or f"usuario{legado.pk}")[:120]
        username = prefixo
        contador = 1

        while User.objects.filter(username=username).exists():
            contador += 1
            username = f"{prefixo}-{contador}"

        user = User.objects.create(
            username=username,
            first_name=legado.nome[:150],
            email = legado.email,
            password = make_password(None),
            is_active = True,        
        )
        Perfil.objects.create(usuario_id=user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_adiciona_perfil'),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            copiar_usuarios,
            reverse_code=migrations.RunPython.noop,
        )
    ]

