# Generated by Django 6.0.7 on 2026-08-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_migra_usuarios_legados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
