# Generated by Django 6.0.7 on 2026-08-02 15:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=17)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('editora', models.CharField(max_length=100)),
                ('cdd', models.CharField(max_length=3)),
                ('local_estante', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=50)),
                ('quant_total', models.CharField(max_length=10)),
                ('exemp_disponiveis', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livros.categoria')),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
