# Generated by Django 6.0.7 on 2026-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=17)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.DateField()),
                ('editora', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('cdd', models.CharField(max_length=3)),
                ('local_estante', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=50)),
                ('quant_total', models.CharField(max_length=10)),
                ('exemp_disponiveis', models.CharField(max_length=10)),
            ],
        ),
    ]
