# Generated by Django 6.0.7 on 2026-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='ano',
            new_name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='livros',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
