# Generated by Django 6.0.7 on 2026-08-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_renomeia_modelos_e_campos'),
        ('emprestimos', '0002_renomeia_modelos_e_campos'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
