# Generated by Django 6.0.7 on 2026-08-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_renomeia_modelo_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='exemp_disponiveis',
            new_name='quantidade_disponivel',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='quant_total',
            new_name='quantidade_total',
        ),
    ]
