# Generated by Django 6.0.7 on 2026-08-16 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_renomeia_campos_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ('titulo',), 'verbose_name': 'livro', 'verbose_name_plural': 'livros'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano de publicação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livros.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='cdd',
            field=models.CharField(max_length=10, verbose_name='CDD'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='etiqueta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=17, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='local_estante',
            field=models.CharField(max_length=100, verbose_name='local na estante'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='subtítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(db_index=True, max_length=150, verbose_name='título'),
        ),
        migrations.AddConstraint(
            model_name='livro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_total__gte', 1)), name='livro_quantidade_total_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='livro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_disponivel__gte', 0)), name='livro_disponivel_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='livro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_disponivel__lte', models.F('quantidade_total'))), name='livro_disponivel_lte_total'),
        ),
    ]
