# Generated by Django 6.0.7 on 2026-08-18 00:21

import livros.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_fortalece_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=17, unique=True, validators=[livros.validators.validar_isbn], verbose_name='ISBN'),
        ),
    ]
