# Generated by Django 6.0.7 on 2026-07-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
