# Generated by Django 6.0.7 on 2026-07-31 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('livros', '0006_remove_livros_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.alunos')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livros.livros')),
            ],
        ),
    ]
