# Generated by Django 6.0.7 on 2026-08-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_termino',
            new_name='data_prevista',
        ),
    ]
