# Generated by Django 6.0.7 on 2026-08-16 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_fortalece_dominio'),
        ('emprestimos', '0002_renomeia_modelos_e_campos'),
        ('livros', '0004_fortalece_dominio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ('-criado_em',), 'permissions': [('pode_devolver_emprestimo', 'Pode registrar devolução'), ('pode_renovar_emprestimo', 'Pode renovar empréstimo')]},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='devolução realizada'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='renovacoes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ATRASADO', 'Atrasado'), ('DEVOLVIDO', 'Devolvido')], db_index=True, default='ATIVO', max_length=10, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(verbose_name='devolução prevista'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='livros.livro'),
        ),
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.CheckConstraint(condition=models.Q(('data_prevista__gte', models.F('data_inicio'))), name='emprestimo_previsao_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.CheckConstraint(condition=models.Q(('data_devolucao__isnull', True), ('data_devolucao__gte', models.F('data_inicio')), _connector='OR'), name='emprestimo_devolucao_gte_inicio'),
        ),
    ]
